import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

group 'com.alexmercerind.media_kit_libs_android_video'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.alexmercerind.media_kit_libs_android_video'
    }

    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }

    dependencies {
        implementation fileTree(dir: "$buildDir/output", include: "*.jar")
    }
}

task downloadDependencies(type: Exec) {   
        // Delete previously created /output subdirectory.

        def outputDir = file("$buildDir/output")
        if (outputDir.exists()) {
            outputDir.deleteDir()
        }
        outputDir.mkdirs()

        // Download all *.jar dependencies & verify their MD5 checksums.
        def filesToDownload = [
            ["url": "https://github.com/ister-app/libmpv-android-video-build/releases/download/v1.2.0/default-arm64-v8a.jar", "md5": "b2216dd26e03270d0aaddb81a4dd5e33", "destination": file("$buildDir/v1.2.0/default-arm64-v8a.jar")],
            ["url": "https://github.com/ister-app/libmpv-android-video-build/releases/download/v1.2.0/default-armeabi-v7a.jar", "md5": "848c48160672e0d5e1a7b6f5119b3a55", "destination": file("$buildDir/v1.2.0/default-armeabi-v7a.jar")],
            ["url": "https://github.com/ister-app/libmpv-android-video-build/releases/download/v1.2.0/default-x86_64.jar", "md5": "df66fcacbf9776f72cf874bfa4efbf2c", "destination": file("$buildDir/v1.2.0/default-x86_64.jar")],
            ["url": "https://github.com/ister-app/libmpv-android-video-build/releases/download/v1.2.0/default-x86.jar", "md5": "279f787af920b22296a8b1a68c30cc6a", "destination": file("$buildDir/v1.2.0/default-x86.jar")]
        ]

        filesToDownload.each { fileInfo ->
            def destFile = fileInfo.destination
            if (destFile.exists()) {
                def calculatedMD5 = MessageDigest.getInstance("MD5").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()

                if (calculatedMD5 != fileInfo.md5) {
                    destFile.delete()
                    println "MD5 mismatch. File deleted: ${destFile}"
                }

            }

            if (!destFile.exists()) {
                destFile.parentFile.mkdirs()
                println "Downloading file from: ${fileInfo.url}"
                destFile.withOutputStream { os ->
                    os << new URL(fileInfo.url).openStream()
                }

                def calculatedMD5 = MessageDigest.getInstance("MD5").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()
                if (calculatedMD5 != fileInfo.md5) {
                    throw new GradleException("MD5 verification failed for ${destFile}")
                }
            }

            copy {
                from destFile
                into outputDir
            }
        }
}

assemble.dependsOn(downloadDependencies)